# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Prénom')),
                ('family_name', models.CharField(max_length=50, verbose_name='Nom de famille')),
                ('gender', models.CharField(choices=[('M', 'Homme'), ('W', 'Femme'), ('U', 'Unknown')], max_length=1, verbose_name='Genre')),
            ],
        ),
    ]
