# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneaFamilyCore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='img_upload',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo'),
        ),
    ]
